all: check run
check:
	@if [ ! -d "~/home/elhussein/6716-lab2/backupdir/" ];then mkdir -p backupdir; fi	   
run:														 	
	@./backupd.sh /home/elhussein/6716-lab2/dir/ /home/elhussein/6716-lab2/backupdir/ 5 10

